DUPUS_WEB/Controllers/GanttController.cs
using DUPUS_WEB.Models;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.EJ2.Base;
using static DUPUS_WEB.Models.ProjectData2;

namespace DUPUS_WEB.Controllers
{
    public partial class GanttController : Controller
    {
        public List<GanttDataSourceDto> DataList = new();

        public IActionResult Index()
        {
            ViewBag.ProjectResources = GetResource();
            return View();
        }

        public IActionResult UrlDatasource([FromBody] DataManagerRequest dm)
        {
            ProjectData2 projectData = new ProjectData2();
            DataList = projectData.GetUrlDataSource();
            return dm.RequiresCounts ? Json(new { result = DataList, count = DataList.Count }) : Json(DataList);
        }


        public IActionResult BatchUpdate([FromBody] CRUDModel batchmodel)
        {
            if (batchmodel != null)
            {
                if (batchmodel.Changed != null)
                {
                    for (var i = 0; i < batchmodel.Changed.Count(); i++)
                    {
                        var value = batchmodel.Changed[i];
                        Console.WriteLine(value);
                        //GanttDataSource result = DataList.Where(or => or.taskId == value.taskId).FirstOrDefault();
                        //result.taskId = value.taskId;
                        //result.taskName = value.taskName;
                        //result.startDate = value.startDate;
                        //result.endDate = value.endDate;
                        //result.duration = value.duration;
                        //result.progress = value.progress;
                        //result.predecessor = value.predecessor;
                        //result.resources = value.resources;
                        //result.parentID = value.parentID;
                        //result.customColumn = value.customColumn;
                    }
                }
                if (batchmodel.Deleted != null)
                {
                    for (var i = 0; i < batchmodel.Deleted.Count(); i++)
                    {
                        var value = batchmodel.Deleted[i];
                        Console.WriteLine(value);
                        //DataList.Remove(DataList.Where(or => or.taskId == batchmodel.Deleted[i].taskId).FirstOrDefault());
                        //RemoveChildRecords(batchmodel.Deleted[i].taskId);
                    }
                }
                if (batchmodel.Added != null)
                {
                    for (var i = 0; i < batchmodel.Added.Count(); i++)
                    {
                        var value = batchmodel.Added[i];
                        Console.WriteLine(value);
                        //DataList.Insert(0, batchmodel.Added[i]);
                    }
                }
            }
            return Json(new { addedRecords = batchmodel?.Added, changedRecords = batchmodel?.Changed, deletedRecords = batchmodel?.Deleted, result = DataList, count = DataList.Count });
        }


        public static List<ResourceGroupCollection> GetResource()
        {
            List<ResourceGroupCollection> GanttResourcesCollection = new List<ResourceGroupCollection>();

            ResourceGroupCollection Record1 = new ResourceGroupCollection()
            {
                resourceId = 1,
                resourceName = "Martin Tamer"
            };
            ResourceGroupCollection Record2 = new ResourceGroupCollection()
            {
                resourceId = 2,
                resourceName = "Rose Fuller"
            };
            ResourceGroupCollection Record3 = new ResourceGroupCollection()
            {
                resourceId = 3,
                resourceName = "Margaret Buchanan"
            };
            ResourceGroupCollection Record4 = new ResourceGroupCollection()
            {
                resourceId = 4,
                resourceName = "Fuller King"
            };
            ResourceGroupCollection Record5 = new ResourceGroupCollection()
            {
                resourceId = 5,
                resourceName = "Davolio Fuller"
            };
            ResourceGroupCollection Record6 = new ResourceGroupCollection()
            {
                resourceId = 6,
                resourceName = "Van Jack"
            };
            GanttResourcesCollection.Add(Record1);
            GanttResourcesCollection.Add(Record2);
            GanttResourcesCollection.Add(Record3);
            GanttResourcesCollection.Add(Record4);
            GanttResourcesCollection.Add(Record5);
            GanttResourcesCollection.Add(Record6);
            return GanttResourcesCollection;
        }

        public class ResourceGroupCollection
        {
            public int resourceId { get; set; }
            public string? resourceName { get; set; }
        }
    }
}

DUPUS_WEB/Controllers/ResourceController.cs
using DUPUS_WEB.Models;
using Entities.Dtos;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using Syncfusion.EJ2.Base;

namespace DUPUS_WEB.Controllers
{
    public class ResourceController : Controller
    {
        private readonly IServiceManager _serviceManager;
        private ProjectData datasource;
        public ResourceController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
            datasource = new ProjectData(_serviceManager);

        }

        public IActionResult Index()
        {
            ViewBag.projectResources = datasource.ProjectResources();
            return View();
        }

        public List<GanttDataSource> DataList = new();

        public IActionResult UrlDatasource([FromBody] DataManagerRequest dm)
        {
            DataList = datasource.GetUrlDataSource();
            var count = DataList.Count();
            return dm.RequiresCounts ? Json(new { result = DataList, count = count }) : Json(DataList);
        }

        public IActionResult BatchUpdate([FromBody] CRUDModel batchmodel)
        {
            if (batchmodel != null)
            {
                if (batchmodel.Changed != null)
                {
                    for (var i = 0; i < batchmodel.Changed.Count(); i++)
                    {
                        var value = batchmodel.Changed[i];
                        Console.WriteLine(value);
                    }
                }
                if (batchmodel.Deleted != null)
                {
                    for (var i = 0; i < batchmodel.Deleted.Count(); i++)
                    {
                        var value = batchmodel.Deleted[i];
                        //Console.WriteLine(value);
                    }
                }
                if (batchmodel.Added != null)
                {
                    for (var i = 0; i < batchmodel.Added.Count(); i++)
                    {
                        var value = batchmodel.Added[i];
                        //Console.WriteLine(value);
                    }
                }
            }
            return Json(new { addedRecords = batchmodel?.Added, changedRecords = batchmodel?.Changed, deletedRecords = batchmodel?.Deleted, result = DataList, count = DataList.Count });
        }


    }
}

DUPUS_WEB/Controllers/ResourceSchedulerController.cs
using DUPUS_WEB.Models;
using Entities.Dtos;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using Syncfusion.EJ2.Base;

namespace DUPUS_WEB.Controllers
{
    public class ResourceSchedulerController : Controller
    {
        private readonly IServiceManager _serviceManager;
        private ProjectData datasource;

        public ResourceSchedulerController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
            datasource = new ProjectData(_serviceManager);
        }

        public IActionResult Index()
        {
            ViewBag.ResourceList = datasource.ResourcesList();
            ViewBag.SelectedResource = "KUTULAMA ISTASYONU";
            return View();
        }

        public IActionResult LoadData([FromBody] DataManagerRequest dm)
        {
            List<SchedulerData> appData = new List<SchedulerData>();
            appData.Add(new SchedulerData
            { id = 1, subject = "Explosion of Betelgeuse Star", startTime = new DateTime(2022, 2, 11, 9, 30, 0), endTime = new DateTime(2022, 2, 11, 11, 0, 0) });

            var count = appData.Count();
            return dm.RequiresCounts ? Json(new { result = appData, count = count }) : Json(appData);
        }

        // Here we get the Start and End Date and based on that can filter the data and return to Scheduler
        //public ActionResult LoadData()  
        //{
        //    List<SchedulerData> appData = new List<SchedulerData>();
        //    appData.Add(new SchedulerData
        //    { id = 1, subject = "Explosion of Betelgeuse Star", startTime = new DateTime(2022, 2, 11, 9, 30, 0), endTime = new DateTime(2022, 2, 11, 11, 0, 0) });
        //    //appData.Add(new SchedulerData
        //    //{ Id = 2, Subject = "Thule Air Crash Report", StartTime = new DateTime(2022, 2, 12, 12, 0, 0), EndTime = new DateTime(2022, 2, 12, 14, 0, 0) });
        //    //appData.Add(new SchedulerData
        //    //{ Id = 3, Subject = "Blue Moon Eclipse", StartTime = new DateTime(2022, 2, 13, 9, 30, 0), EndTime = new DateTime(2022, 2, 13, 11, 0, 0) });
        //    //appData.Add(new SchedulerData
        //    //{ Id = 4, Subject = "Meteor Showers in 2022", StartTime = new DateTime(2022, 2, 14, 13, 0, 0), EndTime = new DateTime(2022, 2, 14, 14, 30, 0) });
        //    //appData.Add(new SchedulerData
        //    //{ Id = 5, Subject = "Milky Way as Melting pot", StartTime = new DateTime(2022, 2, 15, 12, 0, 0), EndTime = new DateTime(2022, 2, 15, 14, 0, 0) });

        //    //var data = db.ScheduleEventDatas.ToList();
        //    return Json(appData);
        //}

    }
}

DUPUS_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DUPUS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DUPUS_WEB.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/21.1.35/material.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DUPUS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gantt" asp-action="Index">Work Order Gantt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Resource" asp-action="Index">Resource Gantt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ResourceScheduler" asp-action="Index">Recource Scheduler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DUPUS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/dist/ej2.min.js"></script>
    <ejs-scripts></ejs-scripts>
    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>